### ISSUE TITLE
Why vtp files are generated in ASCII format?

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-vtk#203]
Hi @devngc, Is there any reason that we are generating the files in ASCII format? I thought we changed the default format to be binary? I noticed the files that Nick is using for results visualization are all in ASCII format.

**Comment by devngc** [comment]
I was surprised to see that while trying to use JoinedPolydata for grids. It's something that's been there after your refactor. I will fix it.

**Comment by devngc** [comment]
I have fixed this on the cli-translate-data branch.
